#!/usr/bin/env python3
import os, subprocess, requests, argparse, re
from bs4 import BeautifulSoup
from configparser import ConfigParser

BLACKLIST = '/etc/pacman.d/blacklist.conf'
CACHE_DIR = '/var/cache/pacman/pkg'

def downgrade_pkgs(pkg_dirs: list[str]):
    subprocess.run(["pacman", "-U"] + pkg_dirs)

def write_to_blacklist_config(pkgs: list[str]):
        with open(BLACKLIST, 'w') as f:
            f.write('[options]\n')
            f.write(f"IgnorePkg = {' '.join(pkgs)}\n")

def remove_ignore_pkgs(pkgs: list[str]):
    if os.path.exists(BLACKLIST):
        config = ConfigParser()
        config.read(BLACKLIST)

        current_ignore_pkg = config.get("options", "IgnorePkg", fallback="")
        ignore_pkg_list = current_ignore_pkg.split()

        for pkg in pkgs:
            ignore_pkg_list.remove(pkg)

        write_to_blacklist_config(ignore_pkg_list)
        print(f"Packages {pkgs} were removed from blacklist")


def ignore_pkgs(pkgs: list[str]):
    pacman_default_config = '/etc/pacman.conf'

    with open(pacman_default_config, 'r') as fr:
        import_str = f"Include = {BLACKLIST}"

        if import_str not in fr.read():
            with open(pacman_default_config, 'a') as fa:
                # If our blacklist config is not in pacman config, append it
                fa.write(import_str + '\n')

    if not os.path.exists(BLACKLIST):
        write_to_blacklist_config(pkgs)

    else:
        config = ConfigParser()
        config.read(BLACKLIST)

        current_ignore_pkg = config.get("options", "IgnorePkg", fallback="")
        ignore_pkgs_list = current_ignore_pkg.split()

        for pkg in pkgs:
            if pkg not in ignore_pkgs_list:
                ignore_pkgs_list.append(pkg)

        write_to_blacklist_config(ignore_pkgs_list)

def find_cached(queries: list[str]) -> None:
    for d in os.listdir(CACHE_DIR):
        for query in queries:
            if d.endswith('.sig'):
                continue

            if re.match(rf"^{query}-\d", d):
                print(os.path.join(CACHE_DIR, d))

def is_matching_package(basename: str, name: str, version: str) -> bool:
    if basename.endswith(".sig"):
        return False

    if not basename.startswith(name):
        return False 

    basename_version = basename.lstrip(name + "-")

    if not basename_version.startswith(version):
        return False

    return True

def get_cached_version(pkg: str, version: str) -> str | None:
    for d in os.listdir(CACHE_DIR):
        if is_matching_package(d, pkg, version):
            return os.path.join(CACHE_DIR, d)

def get_previous_cached_version(pkg: str, current_version: str) -> str | None:
    current_version_index = None
    dirs = sorted(
        (d for d in os.listdir(CACHE_DIR) if d.startswith(pkg) and not d.endswith('.sig')),
        reverse=True
    )

    for i in range(len(dirs)):
        if current_version in dirs[i]:
            current_version_index = i
            break
    
    if current_version_index < len(dirs)-1:
        return os.path.join(CACHE_DIR, dirs[i+1])

    return None

def get_remote_version(pkg: str, version: str) -> str | None:
    url = f'https://archive.archlinux.org/packages/{pkg[0]}/{pkg}'
    response = requests.get(url)

    if response.status_code == 200:
        soup = BeautifulSoup(response.content, 'html.parser')
        links = soup.find_all('a')

        for link in links:
            href: str = link.get('href')
            remote_version = href.replace(pkg + "-", "")

            if href and (remote_version.startswith(version)) and not remote_version.endswith('.sig'):
                return url + '/' + href

    else:
        print(f"Failed to retrieve the URL. Status code: {response.status_code}")

def get_downgrade_version(
    pkg: str, 
    version: str, 
    do_force: bool = False
) -> str:
    package_info = subprocess.run(["pacman", "-Q", pkg], text=True, capture_output=True)

    if package_info.returncode != 0:
        print(f'Package "{pkg}" is not installed or does not exist.')
        exit(1)

    current_version = package_info.stdout.split()[-1]
    cached_version = None

    if version in current_version and not do_force:
        print(f'Provided version "{version}" is currently used ("{current_version}")')
        exit(1)

    if version == "previous":
        cached_version = get_previous_cached_version(pkg, current_version)
    else:
        cached_version = get_cached_version(pkg, version)
    
    if cached_version:
        print(f"Found desired version: {cached_version}")
        return cached_version

    else:
        found_version_url = get_remote_version(pkg, version)

        if found_version_url:
            print(f"Found desired remote version: {found_version_url}")
            return found_version_url

        else:
            print(f"No version {version} found for {pkg}")
            exit(1)

def main(args: argparse.Namespace): 
    if (args.ignore_remove or len(args.packages)) and os.geteuid() != 0:
        print("Error: downgrade must be executed as root")
        return 1

    if args.find:
        find_cached(args.find)

    if args.ignore_remove:
        remove_ignore_pkgs(args.ignore_remove)

    if len(args.packages):
        pkgs_paths = []
        pkgs_names = []

        if len(args.packages) == 1:
            pkg = args.packages[0]
            found_pkg_path = get_downgrade_version(pkg, "previous", args.force)

            pkgs_paths.append(found_pkg_path)
            pkgs_names.append(pkg)

        else:
            for pkg, version in zip(args.packages, args.versions):
                found_pkg_path = get_downgrade_version(pkg, version, args.force)
                pkgs_paths.append(found_pkg_path)
                pkgs_names.append(pkg)

        try:
            downgrade_pkgs(pkgs_paths)

        except KeyboardInterrupt:
            return 1

        if args.ignore:
            print(f"Adding {' '.join(pkgs_names)} to ignore list...")
            ignore_pkgs(pkgs_names)
    

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Downgrade specified packages to given versions or get cached versions.',
        epilog="Ignored packages can be found in /etc/pacman.d/blacklist.conf"
    )
    
    parser.add_argument('packages',              metavar='PACKAGE',  nargs='*', help='package[s] with corresponding version in the format: <PACKAGE> <VERSION>. If Only <PACKAGE> is provided, downgrade to previous version')
    parser.add_argument('-f', '--find',          metavar='PACKAGE',  nargs='+', help='print cached versions for the specified package[s]')
    parser.add_argument('-I', '--ignore-remove', metavar='PACKAGE',  nargs='+', help='remove provided package[s] from ignorelist')
    parser.add_argument('-i', '--ignore',        action='store_true',           help='if downgrading package, add downgraded packages to ignorelist')
    parser.add_argument('--force',               action='store_true',           help='downgrade package even if provided version is the same as installed')

    args = parser.parse_args()
    
    if (len(args.packages) % 2 != 0) and len(args.packages) != 1:
        parser.error("Each package must have a corresponding version.")
        exit(1)

    exit(main(args))
